apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  TELEGRAM_BOT_NAME: "{{ .Values.ut_telegram_bot_name }}"
  TELEGRAM_BOT_TOKEN: "{{ .Values.ut_telegram_bot_token }}"
  ACTIVITY_API_BASE_URL: "{{ .Values.activity_api_base_url }}"
  STORY_API_BASE_URL: "{{ .Values.story_api_base_url }}"
  LOG_LEVEL: "{{ .Values.ut_log_level }}"
  concurrent_updates: "{{ .Values.ut_concurrent_updates }}"
  pool_timeout: "{{ .Values.ut_pool_timeout }}"
  connection_pool_size: "{{ .Values.ut_connection_pool_size }}"

