### Default variable file for storysakhi-service ###

namespace: ""
imagepullsecrets: ""
dockerhub: ""
ss_repository: ""
ss_image_tag: ""
ss_log_level: "INFO"
ss_open_api_key: ""
ss_bhasini_endpoint_url: ""
ss_bhasini_api_key: ""
ss_oci_endpoint_url: ""
ss_oci_region_name: ""
ss_oci_bucket_name: ""
ss_oci_access_key: ""
ss_oci_secret_key: ""

replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 8000
  targetport: 8000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

#{{ storysakhi_liveness_readiness | to_nice_yaml }}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""
