### Default variable file for webstatic-service ###
environment: "dev"
telemetry_host: ""
telemetry_api_token: ""
superset_host: ""
dashboard_ids: "" # Array of values


namespace: ""
imagepullsecrets: ""
dockerhub: ""


replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 8000
  targetport: 8000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""
