apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  telemetry_pg_db: "{{ .Values.telemetry_pg_db}}"
  telemetry_pg_username: "{{ .Values.telemetry_pg_username }}"
  telemetry_pg_password: "{{ .Values.telemetry_pg_password }}"
  telemetry_pg_host: "{{ .Values.telemetry_pg_host }}"
  telemetry_pg_tablename: "{{ .Values.telemetry_pg_tablename }}"
  telemetry_dataextract: "{{ .Values.telemetry_dataextract }}"
  telemetry_local_storage_type: "{{ .Values.telemetry_local_storage_type }}"
  telemetry_environment: "{{ .Values.environment }}"
  telemetry_pg_ssl: "{{ .Values.telemetry_pg_ssl }}"
  telemetry_superset_admin_username: "{{ .Values.telemetry_superset_admin_username }}"
  telemetry_superset_admin_password: "{{ .Values.telemetry_superset_admin_password }}"
  telemetry_superset_host: "{{ .Values.telemetry_superset_host }}"
