### Default variable file for whatsapp-bot-service ###

namespace: ""
imagepullsecrets: ""
dockerhub: ""

replicaCount: 1
whatsapp_repository: "whatsappbot"
whatsapp_image_tag: "latest"
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 3010
  targetport: 3010
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

#{{ whatsappbot_liveness_readiness | to_nice_yaml }}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""

wa_story_sakhi_endpoint_url: ""
wa_activity_sakhi_endpoint_url: ""
wa_char_limit: "1024"
wa_netcore_token: "random1value"
wa_telemetry_service_url: ""
wa_port: "3010"
wa_api_token: ""
wa_bot_api_token: ""
wa_provider_token: ""
wa_provider_number: ""
wa_provider_appname: "TestDJP"
wa_app_env: "dev"
wa_app_name: "djp"
wa_postgres_url: ""
