namespace: ""
imagepullsecrets: devregistrysecrett
dockerhub: hyd.ocir.io/ax2cel5zyviy/ekstep-djp

replicaCount: 1
repository: "adminutil"
image_tag: "release-4.5.0_RC3_68b1eaa_1"
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
network:
  port: 4000
  targetport: 4000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

healthcheck: true
readinessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 2
livenessProbe:
  httpGet:
    path: /health
    port: 4000
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
